#pragma config(Sensor, dgtl11, bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl12, bumpSwitch2,    sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           rightMotor2,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           leftMotor2,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           flashlight,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task move(){
	while(true){
		while(SensorValue(bumpSwitch) == 0 && SensorValue(bumpSwitch2) == 0){
			motor[rightMotor] = -30;
			motor[leftMotor]  = -30;
			motor[rightMotor2] = -30;
			motor[leftMotor2]  = -30;
		}
		motor[rightMotor] = 30;	//Set this to zero if you don't want it to back up and ram forward
		motor[leftMotor]  = 30; //   <-----
		motor[rightMotor2] = 30;
		motor[leftMotor2] = 30;
		sleep(1000);
	}
}
task main()
{
	startTask(move);
	while(true){
		motor[flashlight] = 50;	//I think we are using a flashlight I need to double check
		sleep(750);
		motor[flashlight] = 0;
		sleep(250);
	}
}
// Working on Vex 2.0 Buggy Bot Virtual Worlds
// Buggy Bot has no flashlight though
